flowchart LR

    A[Player Movement]

    A --> B[Width]
    A --> C[Depth]
    A --> D[Rotation]
    A --> E[Overload]

    B --> F[More Space]
    C --> F
    D --> F
    E --> F

    F --> G[Better Chances]