flowchart TD

    A[Formation]

    A --> B[Player Roles]
    A --> C[Mentality]
    A --> D[Team Instructions]

    B --> E[Team Shape]
    C --> E
    D --> E

    E --> F[Attacking Behaviour]
    E --> G[Defensive Behaviour]